CREATE TABLE ForFkTestingBar (
	[ID] [int] IDENTITY(1,20) NOT FOR REPLICATION NOT NULL,
	[baf] [nvarchar](50) NOT NULL,
	CONSTRAINT [ForFkTestingBar_PK] PRIMARY KEY CLUSTERED ( [ID] ASC )
) ON [PRIMARY]
GO
